Feature :  Trending and popular API call
HNTQ/Movie-Search-CS50 pull request #43
Opened 2021-12-06 07:05 UTC by joshuaVayer

Functions to query required data for homepage

2021-12-06 07:08 UTC, joshuaVayer commented on api_client/api_client.py
> +API_KEY = getenv("API_KEY")
Est ce que tu peux me dire si ça fonctionne chez toi avec `getenv` ?

2021-12-06 07:08 UTC, joshuaVayer commented on package.json
> +    "start": "python app.py"
Nous permettra de mettre en place la purge de Tailwind. Je sais pas ce que ça implique pour heroku. J'imagine qu'il faudra le changer dans le procfile

2021-12-06 07:08 UTC, joshuaVayer commented on routes/general/general.py
> +    return result
TEMPORAIRE ⚠️ . Il te suffit de démarrer le serveur pour voir les réponses que l'on récupère

2021-12-08 20:35 UTC, HNTQ commented on api_client/api_client.py
> +API_KEY = getenv("API_KEY")
On l'utilise déja pas mal dans notre code: 
- [model_test.py](https://github.com/HNTQ/Movie-Search-CS50/blob/20d22301821994ba64e32144e87b95ea4b7130d5/model_test.py#L12)
- [model.py](https://github.com/HNTQ/Movie-Search-CS50/blob/20d22301821994ba64e32144e87b95ea4b7130d5/models.py#L97)
- [auth.py](https://github.com/HNTQ/Movie-Search-CS50/blob/20d22301821994ba64e32144e87b95ea4b7130d5/helpers/auth.py#L20) la ou on gère notre mail. 

Donc je valide :)

2021-12-08 23:13 UTC, HNTQ requested changes
Juste le import qui me parait inutile. sinon tout est ok pour moi 👍

2021-12-08 23:13 UTC, HNTQ commented on api_client/__init__.py
> +    query_trending,
ici tu import query_trending alors que les données sont retournées grace à get_index_data.
et il n'est pas réutilisé dans le code par la suite

2021-12-08 23:13 UTC, HNTQ commented on package.json
> +    "start": "python app.py"
actuellement on utilise gunicorn qui lance le app.py. 
A voir si on ne peut pas faire la purge avant de push sur heroku. 
Je propose qu'on fasse un repo POC pour ce sujet

2021-12-08 23:13 UTC, HNTQ commented on routes/general/general.py
> +    return result
ça marche.
Sinon on aurait pu afficher les json comme on faisait sur les autres pages?

2021-12-09 21:06 UTC, HNTQ approved these changes
top

2021-12-09 21:06 UTC, merged