Feature/add lists
HNTQ/Movie-Search-CS50 pull request #44
Opened 2021-12-09 22:11 UTC by HNTQ

2021-12-10 06:03 UTC, joshuaVayer requested changes
Une question, on fait des listes uniquement  pour les films et pas pour les séries ?

2021-12-10 06:03 UTC, joshuaVayer commented on models.py
> +    def get_lists(user_id: str):
Tu as deux fois `get_lits`

2021-12-10 06:03 UTC, joshuaVayer commented on models.py
> +    def delete_movie_from_list(list_id: str, movie_id: str):
Il faudrait uniformisé add_movie et cette méthode

2021-12-10 06:03 UTC, joshuaVayer commented on models.py
> +    def delete_list(list_id: str):
J’enlèverais les suffix liste. On va déjà utiliser les méthodes de cette maniére: 
```python
List.delete_list(...........

2021-12-10 06:03 UTC, joshuaVayer commented on models.py
> +    def get_movie(movie_id: str):
Pareil ici, je propose juste `get` et `delete`

2021-12-10 06:04 UTC, joshuaVayer commented
Etrange l'historique de la PR non ?

2021-12-10 06:57 UTC, HNTQ commented on models.py
> +    def get_lists(user_id: str):
Exact. La première devrait être get_list Sans le s et changer user_id par Id. L'une sert à récupérer le détail d'une liste. L'autre la liste des listes.

2022-01-09 16:30 UTC, joshuaVayer reviewed
Juste le petit commentaire que j'ai mit mais aprés c'est bon pour moi 🙂

2022-01-09 16:30 UTC, joshuaVayer commented on models.py
> +    def get_lists(user_id: str):
Mais on ne pourrait pas avoir quelque chose de plus clair du coup comme get_list_details pour la première ?

2022-01-09 22:43 UTC, HNTQ commented on models.py
> +    def get_lists(user_id: str):
si tout a fait, c'est une bonne idée

2022-10-02 19:33 UTC, merged